Pagination feature/protobuf
status-im/nim-waku pull request #237
Opened 2020-10-19 18:25 UTC by staheri14

This PR addresses the following issue https://github.com/status-im/nim-waku/issues/236

2020-10-28 10:46 UTC, decanus requested changes

2020-10-28 10:46 UTC, decanus commented on tests/v2/test_waku_store.nim
> +      decoded_index = Index.init(pb.buffer)
@staheri14 we do not use snake case.

2020-10-28 10:46 UTC, decanus commented on tests/v2/test_waku_store.nim
> +      pagingDirection=PagingDirection.BACKWARD
```suggestion
      pagingDirection = PagingDirection.BACKWARD
```

2020-10-28 10:46 UTC, decanus commented on tests/v2/test_waku_store.nim
>        index=computeIndex(WakuMessage(payload: @[byte 1], contentTopic:"topic 1"))
```suggestion
      index = computeIndex(WakuMessage(payload: @[byte 1], contentTopic:"topic 1"))
```

2020-10-29 01:00 UTC, oskarth commented
@staheri14 can we please rebase this on master and resolve the conflicts?

2020-10-29 01:51 UTC, oskarth approved these changes

2020-10-29 14:44 UTC, decanus requested changes

2020-10-29 14:44 UTC, decanus commented on waku/protocol/v2/waku_store.nim
> +  msg.pagingInfo= ? PagingInfo.init(pagingInfoBuffer)
```suggestion
  msg.pagingInfo = ? PagingInfo.init(pagingInfoBuffer)
```

2020-10-29 14:44 UTC, decanus commented on waku/protocol/v2/waku_store.nim
> +    count.inc
@staheri14 I don't think you need count here?

2020-10-29 14:44 UTC, decanus commented on tests/v2/test_waku_store.nim
> +      res=HistoryResponse(messages: @[wm], pagingInfo:pagingInfo)
```suggestion
      res = HistoryResponse(messages: @[wm], pagingInfo:pagingInfo)
```

2020-10-29 18:03 UTC, decanus commented on waku/protocol/v2/waku_store.nim
> +    count.inc
you can just do `for count, b in data`

2020-10-29 21:47 UTC, closed without merging