Feature/add admin api
status-im/nim-waku pull request #319
Opened 2020-12-10 09:21 UTC by jm-clius

Partial implementation of #301.

#### What is added?
It adds a method to return a list of peers registered on Waku node as per https://github.com/vacp2p/specs/issues/259. For now it simply returns whichever is available of `FilterPeer`, `HistoryPeer` and `SwapPeer` in a single list.

#### What is outstanding?
Returning peers connected for `WakuRelay`. Since the underlying switch does not expose its connections, this requires some peer storing/tracking as in https://github.com/status-im/nim-waku/issues/265

2020-12-11 00:51 UTC, staheri14 requested changes

2020-12-11 00:51 UTC, staheri14 commented on waku/v2/node/jsonrpc/admin_api.nim
> +                    wPeers.len) # Append to the end of the sequence
```suggestion
      result.insert(node.wakuSwap.peers.mapIt(WakuPeer(multiaddr: constructMultiaddrStr(it.peerInfo),
                                                       protocol: WakuSwapCodec,
                                                       connected: node.switch.isConnected(it.peerInfo))),
                    result.len) # Append to the end of the sequence
```

2020-12-11 00:51 UTC, staheri14 commented on waku/v2/node/jsonrpc/admin_api.nim
> +
```suggestion
      result.insert(node.wakuFilter.peers.mapIt(WakuPeer(multiaddr: constructMultiaddrStr(it.peerInfo),
                                                         protocol: WakuFilterCodec,
                                                         connected: node.switch.isConnected(it.peerInfo))),
                    result.len) # Append to the end of the sequence

```

2020-12-11 00:51 UTC, staheri14 commented on waku/v2/node/jsonrpc/admin_api.nim
> +                    wPeers.len) # Append to the end of the sequence
```suggestion
      result.insert(node.wakuStore.peers.mapIt(WakuPeer(multiaddr: constructMultiaddrStr(it.peerInfo),
                                                        protocol: WakuStoreCodec,
                                                        connected: node.switch.isConnected(it.peerInfo))),
                    result.len) # Append to the end of the sequence
```

2020-12-11 00:51 UTC, staheri14 commented on waku/v2/node/jsonrpc/admin_api.nim
> +    return wPeers
```suggestion

```

2020-12-11 00:51 UTC, staheri14 commented on waku/v2/node/jsonrpc/admin_api.nim
> +    var wPeers: seq[WakuPeer] = @[]
```suggestion
```

2020-12-11 00:52 UTC, staheri14 commented
Looks good to me!

2020-12-11 00:58 UTC, staheri14 reviewed
Looks good to me, just added a few suggestions (also changed it from requested changes)

2020-12-11 01:00 UTC, staheri14 reviewed
Looks good to me, just added a few suggestions (also changed it from requested changes)

2020-12-11 07:49 UTC, jm-clius commented
Thanks, @staheri14! We are trying to avoid using `result` as it suppresses useful compiler warnings. It's still used commonly elsewhere, so must be refactored (see https://github.com/status-im/nim-waku/issues/287). The alternative for me here was to return all the selection, filtering and concat logic bundled in a single expression, but I felt it became unreadable. The compromise was for me to use this local variable and be explicit about how it's populated.

2020-12-11 15:28 UTC, staheri14 commented
> Thanks, @staheri14! We are trying to avoid using `result` as it suppresses useful compiler warnings. It's still used commonly elsewhere, so must be refactored (see #287). The alternative for me here was to return all the selection, filtering and concat logic bundled in a single expression, but I felt it became unreadable. The compromise was for me to use this local variable and be explicit about how it's populated.

I see, right! it is good to be refactored  to reflect the new style

2020-12-11 15:28 UTC, staheri14 approved these changes

2020-12-14 05:18 UTC, oskarth approved these changes
LGTM!

2020-12-14 05:20 UTC, oskarth commented
Oh, please update CHANGELOG as well

2020-12-14 07:53 UTC, jm-clius commented
> Oh, please update CHANGELOG as well (one-liner under `Next` section so releases are easier)

Done in d49736b

2020-12-15 15:48 UTC, merged