fix discv5 enr missing udp port
status-im/nim-waku pull request #913
Opened 2022-03-24 17:07 UTC by kaiserd

This PR addresses #906.

This is a minimal fix printing the actually discoverable ENR managed by the discv5 subsystem.

Wakunode holds another ENR that got printed before.
I will look into consolidating these two ENR instances into one in the future (not critial for now).
This PR should be a minimal fix solving this `citical` issue.

2022-03-24 17:23 UTC, richard-ramos approved these changes

2022-03-24 17:27 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | b71e6cfe | [#1](https://ci.status.im/job/nim-waku/job/prs/job/linux/job/PR-913/1/) | 2022-03-24 17:27:26 | ~20 min | `linux` | [:package:`bin`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/wakunode2-220324-170718-b71e6c-linux.bin) |

2022-03-25 07:20 UTC, oskarth approved these changes

2022-03-25 09:28 UTC, jm-clius requested changes
We do still need this to be logged even if discv5 is not enabled for DNS discovery purposes. Alternatives for quick fix then:
a) log both ENRs (with slightly different log messages)
b) if discv5 is enabled, just replace the `node.enr` with the discv5 version once that gets created.

Although (a) is confusing (so should be temporary until we have consolidated the enrs), it's probably our best option as we need to include `dns4` `multiaddrs` fields in the enr for DNS discovery, and this has not been introduced for the discv5 enr yet.

2022-03-25 12:04 UTC, kaiserd commented
Thank you! 
I implemented solution (a).

Because, as you said, this might introduce confusion, I will add an issue regarding consolidating these ENRs soon.
Still, with this solution the fact that there are two ENRs is explicit.

2022-03-25 12:14 UTC, jm-clius approved these changes

2022-03-28 08:29 UTC, merged